name: "Borg Backup"
version: "1.5.3"
slug: "borg-backup"
description: "Secure and efficient backup solution using Borg Backup"
url: "https://github.com/bmanojlovic/home-assistant-addons/borg-backup"
image: "ghcr.io/bmanojlovic/{arch}-borg-backup"
init: false
arch:
  - aarch64
  - amd64
startup: "services"
boot: "manual"
hassio_role: "manager"
hassio_api: true
homeassistant_api: true
auth_api: true
map:
  - homeassistant_config:rw
  - backup:rw
  - addon_config:rw
options:
  # Backup settings
  borg_user: ""
  borg_repo_url: ""
  borg_host: ""
  borg_ssh_params: ""
  borg_passphrase: ""
  borg_reponame: ""
  borg_compression: "zstd"
  borg_backup_keep_snapshots: 5
  borg_exclude_logs: true
  borg_custom_excludes: ""
  borg_backup_debug: false
  
  # Restore settings
  restore_mode: false
  backup_name: ""
  backup_index: 1
schema:
  # Repository settings
  borg_user: "str?"
  borg_repo_url: "str?"
  borg_host: "str?"
  borg_ssh_params: "str?"
  borg_passphrase: "password?"
  borg_reponame: "str?"
  
  # Backup settings
  borg_compression: "list(none|lz4|zstd|zlib|lzma)?"
  borg_backup_keep_snapshots: "int(1,30)"
  borg_exclude_logs: "bool"
  borg_custom_excludes: "str?"
  borg_backup_debug: "bool"
  
  # Restore settings
  restore_mode: "bool"
  backup_name: "str?"
  backup_index: "int(1,50)?"
environment:
  PUBLISH_ENTITIES: "true"
