name: "Borg Backup for Home Assistant"
version: "1.3.3"
slug: "borg-backup"
description: "Secure and efficient backup solution using Borg Backup"
url: "https://github.com/bmanojlovic/home-assistant-borg-backup/"
image: "ghcr.io/bmanojlovic/{arch}-borg-backup"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "manual"
hassio_role: "backup"
hassio_api: true
homeassistant_api: true
auth_api: true
codenotary: "boris@steki.net"
map:
  - homeassistant_config:rw
  - backup:rw
  - addon_config:rw
options:
  borg_user: ""
  borg_repo_url: ""
  borg_host: ""
  borg_ssh_params: ""
  borg_passphrase: ""
  borg_reponame: ""
  borg_compression: "zstd"
  borg_backup_keep_snapshots: 5
  borg_exclude_logs: true
  borg_custom_excludes: ""
  borg_backup_debug: false
schema:
  borg_user: "str?"
  borg_repo_url: "str?"
  borg_host: "str?"
  borg_ssh_params: "str?"
  borg_passphrase: "str?"
  borg_reponame: "str?"
  borg_compression: "str?"
  borg_backup_keep_snapshots: "int(1,)"
  borg_exclude_logs: "bool"
  borg_custom_excludes: "str?"
  borg_backup_debug: "bool"
